using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;
using Newtonsoft.Json.Converters;
using vspheresdk.Cis.Models.Enums;

namespace vspheresdk.Cis.Models
{
    public class CisTaggingTagCreateSpecType 
    {
        /// <summary>
        /// The display name of the tag. The name must be unique within its category.
        /// </summary>
        /// </summary>
        [JsonProperty(PropertyName = "name", Required = Required.AllowNull)]
        public string Name { get; set; }
        /// <summary>
        /// The description of the tag.
        /// </summary>
        /// </summary>
        [JsonProperty(PropertyName = "description", Required = Required.AllowNull)]
        public string Description { get; set; }
        /// <summary>
        /// The unique identifier of the parent category in which this tag will be created.
        /// When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type:
        /// cis.tagging.Category. When operations return a value of this structure as a result, the field will be an identifier for
        /// the resource type: cis.tagging.Category.
        /// </summary>
        /// </summary>
        [JsonProperty(PropertyName = "category_id", Required = Required.AllowNull)]
        public string CategoryId { get; set; }
        /// <summary>
        /// If unset an identifier will be generated by the server
        /// When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type:
        /// cis.tagging.Tag. When operations return a value of this structure as a result, the field will be an identifier for the
        /// resource type: cis.tagging.Tag.
        /// </summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag_id")]
        public string? TagId { get; set; }
    }
}
