using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;
using Newtonsoft.Json.Converters;
using vspheresdk.Stats.Models.Enums;

namespace vspheresdk.Stats.Models
{
    public class VstatsAcqSpecsFilterSpecType 
    {
        /// <summary>
        /// Used to retrieve paged data for larger result sets. The value of this token is generated by server and returned as next
        /// field in the result of AcqSpecs.list operations. Warning: This attribute is available as Technology Preview. These are
        /// early access APIs provided to test, automate and provide feedback on the feature. Since this can change based on
        /// feedback, VMware does not guarantee backwards compatibility and recommends against using them in production
        /// environments. Some Technology Preview APIs might only be applicable to specific environments.
        /// unset the first page of results will be returned.
        /// </summary>
        /// </summary>
        [JsonProperty(PropertyName = "page")]
        public string? Page { get; set; }
    }
}
