using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;
using Newtonsoft.Json.Converters;
using vspheresdk.Stats.Models.Enums;

namespace vspheresdk.Stats.Models
{
    public class VstatsDataDataPointsResultType 
    {
        /// <summary>
        /// List of DataPoints received. Warning: This attribute is available as Technology Preview. These are early access APIs
        /// provided to test, automate and provide feedback on the feature. Since this can change based on feedback, VMware does not
        /// guarantee backwards compatibility and recommends against using them in production environments. Some Technology Preview
        /// APIs might only be applicable to specific environments.
        /// </summary>
        /// </summary>
        [JsonProperty(PropertyName = "data_points", Required = Required.AllowNull)]
        public Dictionary<string,VstatsDataDataPointType> DataPoints { get; set; }
        /// <summary>
        /// The Data.DataPointsResult.next field is a token used to retrieve paged data for larger result sets. This is opaque token
        /// generated by the server. It is to be sent in the Data.FilterSpec.page field to issue a subsequent call to the query
        /// operation for retrieving results that did not fit the current page. Warning: This attribute is available as Technology
        /// Preview. These are early access APIs provided to test, automate and provide feedback on the feature. Since this can
        /// change based on feedback, VMware does not guarantee backwards compatibility and recommends against using them in
        /// production environments. Some Technology Preview APIs might only be applicable to specific environments.
        /// set when there are more results to retrieve.
        /// </summary>
        /// </summary>
        [JsonProperty(PropertyName = "next")]
        public string? Next { get; set; }
    }
}
